[package]
name = "fetch"
version = "0.1.0"
edition = "2018"

[dependencies]
dirs = "3.0.2"
reqwest = { version = "0.11.4", features = ["json"] }
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
tokio = { version = "1.7.1", features = ["full"] }

